In [30]:
import pandas as pd 
import numpy as np 
import keras 
import tensorflow as tf 

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [3]:
data = pd.read_excel(r'D:\NIT Course\NIT Data Science Course\Deep Learning\Churn_Modelling.xlsx')
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
data.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
data.duplicated().sum()

np.int64(0)

In [15]:
X = data.iloc[:, 3:-1].values
y = data.iloc[:,-1].values

In [16]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]],
      shape=(10000, 10), dtype=object)

In [17]:
y

array([1, 0, 1, ..., 1, 1, 0], shape=(10000,))

### Apply Label Encoding on `Gender`

In [19]:
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])
X[:,2]

array([0, 0, 0, ..., 0, 1, 0], shape=(10000,), dtype=object)

### Apply Column Transformar

In [23]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [25]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
X = scale.fit_transform(X)
X

array([[ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-1.00280393, -0.57873591,  1.74273971, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.99720391, -0.57873591, -0.57380915, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.00280393,  1.72790383, -0.57380915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011, -1.07636976]], shape=(10000, 12))

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)

#### Create a ANN Model

In [35]:
model = Sequential()

# Add Input and Hiddne layer 
model.add(Dense(units =32, activation = 'relu'))
model.add(Dense(units=16, activation='relu'))
model.add(Dense(units=8, activation = 'relu'))
model.add(Dense(units=1, activation = 'sigmoid'))

# Compile the model 
model.compile(loss = 'binary_crossentropy', optimizer='adam', metrics=['accuracy'])


# train the model 
history = model.fit(X_train, y_train, epochs = 100, batch_size=32, validation_data=(X_test, y_test))



Epoch 1/100


250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8011 - loss: 0.4715 - val_accuracy: 0.8280 - val_loss: 0.4156
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8279 - loss: 0.4078 - val_accuracy: 0.8385 - val_loss: 0.3885
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8449 - loss: 0.3802 - val_accuracy: 0.8555 - val_loss: 0.3604
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8529 - loss: 0.3578 - val_accuracy: 0.8585 - val_loss: 0.3504
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8585 - loss: 0.3472 - val_accuracy: 0.8575 - val_loss: 0.3431
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8595 - loss: 0.3409 - val_accuracy: 0.8600 - val_loss: 0.3392
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8604 - loss: 0.3378 - val_accuracy: 0.8610 - val_loss: 0.3418
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8633 - loss: 0.3342 - val_accuracy: 0.8555

In [49]:
y_pred_prob = model.predict(X_test)
y_pred_prob

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step


array([[0.34912094],
       [0.25212324],
       [0.16061835],
       ...,
       [0.07475016],
       [0.15096998],
       [0.12958284]], shape=(2000, 1), dtype=float32)

In [52]:
y_pred = (y_pred_prob > 0.5).astype("int32")
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], shape=(2000, 1), dtype=int32)

In [53]:
from sklearn.metrics import accuracy_score , confusion_matrix
ac = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
print('Accuracy Score :', ac)
print('Confusion Matrix :\n', cm)

Accuracy Score : 0.849
Confusion Matrix :
 [[1495  100]
 [ 202  203]]
